# mysql
databaseip: "127.0.0.1"
databasename: "verify"
username: "yourUsername"
password: "yourpassword"

# prefix
verify_prefix_use: true
verify_prefix: "[DCVerify]"

# Mesage Placeholder
# %verifycode% - Gibt deine 6 Stelligen Verify Code aus.
# %verifydcname% - gibt den Verknüpften Account aus.
# %verifyplayer% - gibt den Username aus.

# message
verify_nopermissions: "System fehler Bitte gebe /help ein um alle commands zu sehen."
verify_connsole_message: "&7Du Musst ein Spieler Sein."
verify_code_message: "&7Dein Verify Code Lautet:&a %verifycode% &7."
verify_check_noverifykation: "&7Aktuell bist du mit &akeinem Discored User&7 Verknüpft."
verify_check_verifycode: "&7Dein Verknüpfter Discord Account Lautet:&a %verifydcname% &7."
verify_delete_nodelete: "&7Die Verknüpfung konnte nicht gelöscht werden da du mit §akeinem Discored User&7 Verknüpft bist."
verify_delete_verifykation: "&7Deine Verknüpfung mit:&a %verifydcname% &7wurde gelöscht."
verify_accept_noaccept: "&7Aktuell kannst du §akeine Verknüpfung bestätigen&7 da du keine anfrage hast."
verify_accept_existing: "&7Aktuell bist du mit dem User:&a %verifydcname% &7Verknüpft du kannst die Verknüpfung jederzeit mit &a/Verify delete &7löschen."
verify_accept_accepting: "&7Gebe §a/Verify Accept&7 erneut ein um die Verknüpfung mit:&a %verifydcname% &7zu bestätigt."
verify_accept_successful: "&7Deine Verknüpfung mit:&a %Verifydcname% &7wurde hirmit bestätigt."
verify_help: "&7Bitte gebe &a/Verify &7<§acheck&7/&adelete&7/§aaccept&7> ein."
verify_reload: "&7Reload für DCVerify wurde &aerfolgreich&7 ausgeführt."
verify_reload_error: "&7Reload für DCVerify konnte &cnicht&7 ausgeführt werden."
verify_admin_offline: "&7Der angegeben Spieler ist nicht Online."
verify_admin_delete: "&7Die Verknüpfung von %verifyplayer% wurde gelöscht."



